### ISSUE TITLE
Running README Docker commands on Windows throws an error.

### ISSUE THREAD

**Issue by ghost** [BensonKHuang/StableConfigs#2]
![issue](https://user-images.githubusercontent.com/6019198/74189379-e1878280-4c15-11ea-9b54-9e0bf67bd0ec.PNG)

**Comment by stevenwang5689** [comment]
https://stackoverflow.com/questions/56797665/error-response-from-daemon-drive-has-not-been-shared

**Comment by BensonKHuang** [comment]
Issue is with configuring user Window's settings. Thanks @stevenwang5689 for quick resolution.
